### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by qptain-Nemo** [ngradwohl/bitwig_scripts#1]
I'm trying your sfz to multisample converter with various sfz files I got with Cakewalk MusicCreator and with all of them I get the following exception:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
    at net.localguru.sfz2multisample.Sfz2Multisample.loadSfz(Sfz2Multisample.java:125)
    at net.localguru.sfz2multisample.Sfz2Multisample.main(Sfz2Multisample.java:14)

**Comment by ngradwohl** [comment]
can you please send me the sfz file you try to convert?

**Comment by ngradwohl** [comment]
Fixed with version 1.0.2
